replicaCount: 2
 
image:
  repository: sokolik/user-api
 
service:
  type: NodePort
  port: 8000
 
postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"

ingress:
  enabled: true
  annotations: {
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths: [
        /otusapp($|/)(.*)
      ]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local