replicaCount: 2
 
image:
  repository: sokolik/user-api
 
service:
  type: NodePort
  port: 8000
 
externalPostgresql:
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: "postgres"
  postgresqlPort: "5432"